############
# Database #
############

spring:
  datasource:
    url: jdbc:mysql://eu01-sql.pebblehost.com:3306/customer_613339_tastybot
    username: customer_613339_tastybot
    password: Nji$4VaVI3shxMnCST7$

